# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Compile diffs
run-name: "Compile and compare ${{ github.actor }}'s changes"
on:
  pull_request:
    branches:
      - main

jobs:
  compile-diffs:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
      env:
        TEXINPUTS: ".:..:"
    steps:
      - name: Install latexdiff
        run: apt update && apt install latexdiff -y
      - name: Check out document sources
        uses: actions/checkout@v4
      - name: Create build directory
        run: mkdir build
      - name: list
        run: ls
      - name: Compile statutes
        run: |
          latexmk -outdir=../build -cd stadgar/stadgar.tex
      - name: Compile regulations
        run: |
          latexmk -outdir=../build -cd reglemente/reglemente.tex

      - name: Compile diffs for statutes
        run: |
          latexdiff --flatten --exclude-textcmd="section,subsection,subsubsection,paragraph,subparagraph" \
            --append-safecmd=chapter \
            --append-safecmd=part \
            --append-safecmd=appendix \
            --append-safecmd=frontmatter \
            --append-safecmd=mainmatter \
            --append-safecmd=backmatter \
            stadgar/stadgar.tex stadgar/stadgar.tex > /tmp/stadgar_diff.tex
          latexmk -outdir=../build -cd /tmp/stadgar_diff.tex
      - name: Compile diffs for regulations
        run: |
          latexdiff --flatten --exclude-textcmd="section,subsection,subsubsection,paragraph,subparagraph" \
            --append-safecmd=chapter \
            --append-safecmd=part \
            --append-safecmd=appendix \
            --append-safecmd=frontmatter \
            --append-safecmd=mainmatter \
            --append-safecmd=backmatter \
            reglemente/reglemente.tex reglemente/reglemente.tex > /tmp/reglemente_diff.tex
          latexmk -outdir=../build -cd /tmp/reglemente_diff.tex
      - name: List outputs
        run: ls build
      - name: Upload PDFs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr-pdfs
          path: build/*.pdf
